### ISSUE TITLE
DGI sometimes converges to normal value of a different group

### ISSUE THREAD

**Issue by mcatanzaro** [FREEDM-DGI/FREEDM#380]
During the fault protection portion of the site visit demo, one DGI converged towards the normal of the DGI that it was isolated from, rather than the DGI it was connected to. I've observed this now on at least three separate occasions. The bug is nevertheless not common, only seems to affect at most one DGI per demo when it does occur, and does not always affect the same DGI.

I'm fairly confident that the groups are being formed correctly, so this is more likely a load balancing issue (and will likely be irrelevant once Tom's rewritten load balance is merged) than a group management (topology) issue or configuration mistake.  My guess is that normal was somehow stale, or else that the peer lists that LB manages on its own somehow end up holding peers from outside the current group.

Tom's theory is that it just looks like the DGI is converging to the other group's normal, and it's instead converging to -normal instead of +normal.

**Comment by scj7t4** [comment]
This shouldn't be an issue with re-written load balance.
