### ISSUE TITLE
paho-mqtt3c library on cluster computers

### ISSUE THREAD

**Issue by geoffcline** [FREEDM-DGI/FREEDM#395]
figure out how to get this library installed on the cluter computers

**Comment by geoffcline** [comment]
`find_library(MQTT_LIBRARY NAMES paho-mqtt3c)`

it looks like the website is here: https://www.eclipse.org/paho/ 

However, there are different flavors of the library, unsure which to use

**Comment by scj7t4** [comment]
You have Sudo, feel free to install things as you need them.

**Comment by geoffcline** [comment]
it compiled when i added 

```
/usr/local/include/MQTTClient.h
/usr/local/lib/libpaho-mqtt3c.so
/usr/local/lib/libpaho-mqtt3c.so.1
/usr/local/lib/libpaho-mqtt3c.so.1.0
/usr/local/lib/libpaho-mqtt3cs.so
/usr/local/lib/libpaho-mqtt3cs.so.1
/usr/local/lib/libpaho-mqtt3cs.so.1.0
```

so I will be adding these to the cluster
